name: Samba Server with Drive Mounting
description: Expose Home Assistant folders with SMB/CIFS and external drive mounting
url: https://github.com/medictroy/samba-server
version: 1.0.1
stage: test
slug: sambaexternal
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
# startup: services
startup: initialize
boot: auto
init: false
hassio_api: true
hassio_role: admin
host_network: true
map:
  - addon_config:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - ssl:rw
  - config:rw
  - storage:rw
options:
  custom_config: false
  workgroup: WORKGROUP
  logins:
    - username: homeassistant
      password: null
  local_master: true
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
  automount: true
  moredisks: []
  mountoptions:
    - nosuid
    - relatime
    - noexec
  available_disks_log: true
  medialibrary:
    enable: false
  veto_files:
    - "._*"
    - ".DS_Store"
    - Thumbs.db
    - icon?
    - ".Trashes"
  compatibility_mode: false
#  apple_compatibility_mode: true
  recyle_bin_enabled: true
  wsdd2: false
  wsdd: true
  autodiscovery: {}
  other_users: []
  acl: []
  interfaces: []
schema:
  custom_config: bool
  workgroup: str
  local_master: bool
  logins:
    - username: str
      password: password
  automount: bool?
  moredisks:
    - str
  mountoptions:
    - str
  available_disks_log: bool?
  medialibrary:
    enable: bool?
    ssh_private_key: password?
  allow_hosts:
    - str
  veto_files:
    - str
  compatibility_mode: bool?
  recyle_bin_enabled: bool?
  wsdd: bool
  wsdd2: bool?
  hdd_idle_seconds: int(0,)?
  enable_smart: bool?
  autodiscovery:
    disable_discovery: bool?
    disable_persistent: bool?
    disable_autoremove: bool?
  other_users:
    - username: str
      password: str
#  acl:
#    - share: str
#      disabled: bool?
#      users:
#        - str?
#      ro_users:
#        - str?
#      timemachine: bool?
#      usage: list(media|backup|share)?
  interfaces:
    - str
  bind_all_interfaces: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  meaning_of_life: int?
  multi_channel: bool?

udev: true
#devices:
#  - /dev/disk:/dev/disk:rwm
#  - /dev/fuse:/dev/fuse:rwm
#  - /dev/sda1:/dev:sda1:rwm
#usb: true
host_dbus: true
kernel_modules: true
protected: false
privileged:
  - SYS_ADMIN
#  - DAC_READ_SEARCH
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_MODULE
full_access: true
devicetree: false
apparmor: true
host_ipc: true
advanced: true
homeassistant: 2025.4.0
backup: hot
auth_api: true
homeassistant_api: true
timeout: 60
#ports:
#  - 445/tcp: 445
#  - 139/tcp: 139
#ports_description:
#  - 445/tcp: SMB/CIFS
#  - 139/tcp: NetBIOS Session Service