name: Samba Server with External Mount
description: Expose Home Assistant folders with SMB/CIFS and external drive mounting
url: https://github.com/medictroy/samba-server
version: 1.0.0
stage: stable
slug: samba_external
codenotary: notary@home-assistant.io
startup: services
init: false
boot: auto
hassio_role: admin
hassio_api: true
host_network: true
protected: false # Disable protection mode to allow privileged access
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_MODULE
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/disk:/dev/disk:rwm
  - /dev/fuse:/dev/fuse:rwm
  - /dev/sda1:/dev:sda1:rwm
map:
  - addon_config:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - ssl:rw
  - config:rw
  - storage:rw
ports:
  - 445/tcp: 445
  - 139/tcp: 139
ports_description:
  - 445/tcp: SMB/CIFS
  - 139/tcp: NetBIOS Session Service
options:
  custom_config: false
  workgroup: WORKGROUP
  local_master: true
  allow_hosts:
    - 10.0.0.0/8
  logins:
    - username: homeassistant
      password: null
  automount: true
  moredisks: []
  mountoptions:
    - nosuid
    - relatime
    - noexec
  available_disks_log: true
  medialibrary:
    enable: false
  veto_files:
    - "._*"
    - ".DS_Store"
    - Thumbs.db
    - icon?
    - ".Trashes"
  compatibility_mode: false
  apple_compatibility_mode: true
  recyle_bin_enabled: true
  wsdd2: false
  wsdd: true
  autodiscovery: {}
  other_users: []
  acl: []
  interfaces: []
schema:
  custom_config: bool
  workgroup: str
  local_master: bool
  logins:
    - username: str
      password: password
  automount: bool?
  moredisks:
    - str
  mountoptions:
    - str
  available_disks_log: bool?
  medialibrary:
    enable: bool?
    ssh_private_key: password?
  allow_hosts:
    - str
  veto_files:
    - str
  compatibility_mode: bool?
  recyle_bin_enabled: bool?
  wsdd: bool
  wsdd2: bool?
  hdd_idle_seconds: int(0,)?
  enable_smart: bool?
  autodiscovery:
    disable_discovery: bool?
    disable_persistent: bool?
    disable_autoremove: bool?
  other_users:
    - username: str
      password: str
  acl:
    - share: str
      disabled: bool?
      users:
        - str?
      ro_users:
        - str?
      timemachine: bool?
      usage: list(media|backup|share)?
host_dbus: true
kernel_modules: true
full_access: true
devicetree: false
apparmor: true
host_ipc: true
advanced: true
homeassistant: 2025.4.0
backup: hot
auth_api: true
homeassistant_api: true
